### ISSUE TITLE
Error appeared when I tried to start application server.

### ISSUE THREAD

**Issue by koca2000** [comru/firebird#1]
Hi!
I have downloaded this demo (not by git - not working), changed build.gradle as told in readme. Database was succesfully created, but when I tried to start application server, message bellow appeared and tomcat didn't start.

`Entity com.haulmont.cuba.security.entity.Group has no attribute applicable for table id column`

Almost same error also appeared when I tried to create new Entity and left id type as UUID (other id types seems to be working).

**Comment by comru** [comment]
Hi! 
Can you clarify what version of Firebird and Studio do you use?

**Comment by koca2000** [comment]
Firebird 2.5.8
Studio 6.8.1
